# Generated by Django 4.1.5 on 2023-05-24 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cart',
            table='cart_tb',
        ),
    ]
