# Generated by Django 4.1.5 on 2023-06-12 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_orders'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='customer_id',
            new_name='customer',
        ),
    ]
