# Generated by Django 4.1.5 on 2023-05-15 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='product',
            table='product_tb',
        ),
    ]
