# Generated by Django 4.1.5 on 2023-05-15 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0002_alter_product_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_code',
            new_name='code',
        ),
    ]
