# Generated by Django 4.1.5 on 2023-05-11 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=30)),
                ('e_mail', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=30)),
                ('phone_no', models.BigIntegerField(max_length=10)),
                ('photo', models.ImageField(upload_to='seller/')),
                ('company_name', models.CharField(max_length=30)),
            ],
        ),
    ]
