# Generated by Django 4.1.5 on 2023-05-11 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_seller_ac_holder_name_seller_ac_no_seller_branch_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=30)),
                ('phone', models.BigIntegerField()),
                ('email', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
    ]
