# Generated by Django 4.1.5 on 2023-05-15 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_customer_address'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customer',
            table='customer_tb',
        ),
        migrations.AlterModelTable(
            name='seller',
            table='seller_tb',
        ),
    ]
