# Generated by Django 4.1.5 on 2023-05-17 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_alter_customer_table_alter_seller_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='photo',
            field=models.ImageField(default='', upload_to='customer/'),
        ),
    ]
