# Generated by Django 4.1.5 on 2023-05-23 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='admin',
            table='admin_tb',
        ),
    ]
